name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint fix
        run: npm run lint:fix

      - name: Run Prettier format
        run: npm run format

      - name: Check for uncommitted changes
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          if ! git diff --quiet; then
            echo "❌ Auto-fixes were applied. Please commit the changes locally."
            git --no-pager diff
            exit 1
          fi

      - name: Run lint (post-fix validation)
        run: npm run lint

      - name: Run Prettier check (post-fix validation)
        run: npm run format:check

      - name: Run tests with coverage
        run: npm run test
        env:
          DB_URI: ${{ secrets.TEST_DB_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_EXPIRES_IN: "1d"

