name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint fix
        run: npm run lint:fix

      - name: Run Prettier format
        run: npm run format

      - name: Run lint (post-fix validation)
        run: npm run lint

      - name: Run Prettier check (post-fix validation)
        run: npm run format:check

      - name: Create .env.test.local from GitHub Secrets
        run: |
          echo "DB_URI=${{ secrets.TEST_DB_URI }}" >> .env.test.local
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env.test.local
          echo "JWT_EXPIRES_IN=1d" >> .env.test.local
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> .env.test.local
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env.test.local
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env.test.local

      - name: Run tests with coverage
        run: npm run test
