name: Deploy to GKE

on:
  push:
    branches: [main]
    tags: ["v*"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      REGION: us-east1
      CLUSTER_NAME: filedrop-cluster
      FRONTEND_IMAGE: filedrop-frontend:nginx
      BACKEND_IMAGE: filedrop-backend:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker for GCR
        run: gcloud auth configure-docker

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_IMAGE }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.FRONTEND_IMAGE }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE }} .
          docker push gcr.io/${{ env.PROJECT_ID }}/${{ env.BACKEND_IMAGE }}

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials $CLUSTER_NAME --region $REGION

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/
          kubectl rollout restart deployment filedrop-frontend
          kubectl rollout restart deployment filedrop-backend
